networks:
  roboshop:
    driver: bridge
volumes:
  mongodb:
  mysql:
  rabbitmq:
  redis:
services:
  mongodb:
    image: rajakuma/mongodb:v1
    container_name: mongodb
    networks:
      - roboshop
    volumes:
      - mongodb:/data/db
  catalogue:
    image: rajakuma/catalogue:v1
    container_name: catalogue
    networks:
      - roboshop
    depends_on: 
      - mongodb
  redis:
    image: rajakuma/redis:v1
    container_name: redis
    networks:
      - roboshop
    volumes:
      - redis:/data
  cart:
    image: rajakuma/cart:v1
    container_name: cart
    networks:
      - roboshop
    depends_on:
      - catalogue
      - redis
  user:
    image: rajakuma/user:v2
    container_name: user
    networks:
      - roboshop
    depends_on:
      - mongodb
      - redis
  mysql:
    image: rajakuma/mysql:v1
    container_name: mysql
    networks:
      - roboshop
    volumes:
      - mysql:/var/lib/mysql
  shipping:
    image: rajakuma/shipping:v1
    container_name: shipping
    networks:
      - roboshop
    depends_on:
      - mysql
      - cart
  payment:
    image: rajakuma/payment:v1
    container_name: payment
    networks:
      - roboshop
    depends_on:
      - cart
      - user
      - rabbitmq
  rabbitmq:
    image: rajakuma/rabbitmq:v1
    container_name: rabbitmq
    networks:
      - roboshop
    environment:
      - RABBITMQ_DEFAULT_USER=roboshop
      - RABBITMQ_DEFAULT_PASS=roboshop123
    volumes:
      - rabbitmq:/var/lib/rabbitmq
  web:
    image: rajakuma/web:v1
    container_name: web
    networks:
      - roboshop
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - user
      - cart
      - shipping
