networks:
  roboshop:
    driver: bridge
services:
  mongodb:
    image: raja1475/mongodb:k1
    container_name: mongodb
    networks:
      - roboshop
  catalogue:
    image:  raja1475/catalogue:k1
    container_name: catalogue
    networks:
      - roboshop
    depends_on:
      - mongodb
  redis:
    image: redis
    container_name: redis
    networks:
      - roboshop
  user:
    image: raja1475/user:k1
    container_name: user
    networks:
      - roboshop
    depends_on:
      - mongodb
      - redis
  web:
    image: raja1475/web:k1
    container_name: web
    networks:
      - roboshop
    ports:
    - "80:80"
    depends_on:
      - catalogue
      - user




